name: oneloud_official

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.RELEASE }}-${{ matrix.BRANCH }}-${{ matrix.TYPE == 'desktop' && matrix.DESKTOP_ENVIRONMENT || matrix.TYPE }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        BRANCH:
          - current
        RELEASE:
          - bullseye # Debian 11
        TYPE:
          - minimal
          - cli


    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Build
        run: |
          sudo ./compile.sh \
            BOARD=onecloud \
            BRANCH=${{ matrix.BRANCH }} \
            RELEASE=${{ matrix.RELEASE }} \
            KERNEL_CONFIGURE=no \
            KERNEL_ONLY=no \
            BUILD_MINIMAL=${{ matrix.TYPE == 'minimal' && 'yes' || 'no' }} \
            BUILD_DESKTOP=${{ matrix.TYPE == 'desktop' && 'yes' || 'no' }} \
            EXPERT=yes \
            USE_CCACHE=no \
            NO_APT_CACHER=yes \
            COMPRESS_OUTPUTIMAGE=xz,sha,gpg

      - name: Upload artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: ${{ matrix.RELEASE }}-${{ matrix.BRANCH }}-${{ matrix.TYPE == 'desktop' && matrix.DESKTOP_ENVIRONMENT || matrix.TYPE }}
          path: output/images/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/

      - name: Generate sha256sum
        run: |
          touch sha256sum
          for a in artifacts/*/*.sha; do
            cat "$a" >>sha256sum
            rm -f "$a"
          done

      - name: Show sha256sum
        run: |
          cat sha256sum

      - name: Release
        run: |
          time="${{ github.event.head_commit.timestamp }}"
          sha="${GITHUB_SHA:0:8}"
          tag="Onecloud-official-$(date +'%Y%m%d-%H%M' -d "$time")"
          message="Onecloud-official $(date +'%Y-%m-%d %H:%M' -d "$time")"
          hub release create  -t "$GITHUB_SHA" "$tag" -m "$message" \
            $(for a in artifacts/*/*; do echo -a $a; done) \
            -a sha256sum
        env:
          GITHUB_TOKEN: ${{ github.token }}
